packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.1
  '@tailwindcss/postcss': ^4.1.17
  '@types/bun': ^1.3.3
  '@types/node': ^24.10.1
  cspell: ^9.6.2
  eslint: ^9.39.2
  prettier: ^3.8.1
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.3.6

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - bufferutil
  - core-js-pure
  - esbuild
  - lefthook
  - msw
  - prisma
  - sharp
  - utf-8-validate

overrides:
  '@types/minimatch': 5.1.2

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
