packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@eslint/js': ^9.39.1
  '@tailwindcss/postcss': ^4.1.17
  '@tailwindcss/vite': ^4.1.16
  '@tanstack/react-form': ^1.23.8
  '@types/bun': ^1.3.3
  '@types/node': ^24.10.1
  cspell: ^9.4.0
  eslint: ^9.39.1
  prettier: ^3.7.4
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.1.13

catalogs:
  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.1
    react-dom: ^19.2.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - bufferutil
  - core-js-pure
  - esbuild
  - lefthook
  - msw
  - prisma
  - sharp
  - utf-8-validate

overrides:
  '@types/minimatch': 5.1.2
  vite: 7.1.12

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
